site_name: Reto 0 "Here we go!" -  Equipo 5 > Clemente Rodriguez, Ibai Garcia, Aritz Basarrate.
site_author: Clemente Rodriguez, Ibai Garcia, Aritz Basarrate.
site_url: https://ai-somorrostro.github.io/reto0

theme: kpn
nav:
  - Introducción: index.md
  - BDA: bda.md
  - PIA: pia.md
  - SBD: sbd.md
  - MIA: mia.md
  - SAA: saa.md

repo_url: https://github.com/ai-somorrostro/reto0