{
 "title": "RETO 0 - Dashboard de Criptomonedas v2",
 "time": { "from": "2025-03-16T22:02:47.038Z", "to": "2025-10-06T21:17:53.301Z" },
 "templating": {
  "list": [
   {
    "name": "Criptomoneda",
    "label": "Seleccionar criptomoneda",
    "query": {
     "query": "from(bucket: \"livemarket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cryptocoins\")\n  |> keep(columns: [\"name\"])\n  |> distinct(column: \"name\")\n  |> sort()"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Evolución del precio",
   "type": "timeseries",
   "description": "Muestra cómo varía el precio en USD de la criptomoneda seleccionada a lo largo del tiempo. Es la visualización base: una serie temporal con el valor medio por ventana.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"livemarket\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cryptocoins\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price_usd\")\n  |> filter(fn: (r) => r[\"name\"] == \"${Criptomoneda}\")\n"
    }
   ]
  },
  {
   "title": "Último precio",
   "type": "stat",
   "description": "Último valor de la moneda",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"livemarket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cryptocoins\")\n  |> filter(fn: (r) => r._field == \"price_usd\")\n  |> filter(fn: (r) => r[\"name\"] == \"${Criptomoneda}\")\n  |> last()\n\n"
    }
   ]
  },
  {
   "title": "Cambio porcentual del precio ",
   "type": "gauge",
   "description": "El cambio porcentual en el precio de la moneda durante las últimas 24 horas y los últimos 7 días.\nSirve para ver si la moneda ha subido o bajado recientemente.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"livemarket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cryptocoins\")\n  |> filter(fn: (r) => r._field == \"chg_24h\")\n  |> filter(fn: (r) => r.name == \"${Criptomoneda}\")\n  |> yield(name: \"chg_24h_last\")\n"
    },
    {
     "query": "from(bucket: \"livemarket\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cryptocoins\")\n  |> filter(fn: (r) => r[\"_field\"] == \"chg_7d\")\n  |> filter(fn: (r) => r[\"name\"] == \"${Criptomoneda}\")\n  |> yield(name: \"chg_7d_last\")"
    }
   ]
  },
  {
   "title": "Volumen de compras y ventas",
   "type": "stat",
   "description": "Indica cuánto dinero se ha movido (compras y ventas) en las últimas 24 horas y el total historicamente",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"livemarket\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cryptocoins\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_vol\")\n  |> filter(fn: (r) => r[\"name\"] == \"${Criptomoneda}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"total_vol\")"
    },
    {
     "query": "from(bucket: \"livemarket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cryptocoins\")\n  |> filter(fn: (r) => r._field == \"vol_24h\")\n  |> filter(fn: (r) => r.name == \"${Criptomoneda}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"vol_24h\")"
    }
   ]
  },
  {
   "title": "Capitalización del mercado",
   "type": "timeseries",
   "description": "La capitalización total de la criptomoneda (precio × monedas en circulación)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"livemarket\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cryptocoins\")\n  |> filter(fn: (r) => r[\"_field\"] == \"market_cap\")\n  |> filter(fn: (r) => r[\"name\"] == \"${Criptomoneda}\")\n  |> yield(name: \"market_cap_last\")"
    }
   ]
  },
  {
   "title": "Evolución del precio",
   "type": "timeseries",
   "description": "Es la serie temporal original del precio de a lo largo del tiempo.del tiempo. Esta línea es una predicción estadística calculada a partir de los datos del precio.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"livemarket\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cryptocoins\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price_usd\")\n  |> filter(fn: (r) => r[\"name\"] == \"${Criptomoneda}\")\n"
    }
   ]
  }
 ]
}