
services:
  python-kaggle:
    build:
      context: ./subida_y_procesamiento_datos
    container_name: python_kaggle_runner
    depends_on:
      - grafana
    volumes:
      - ./subida_y_procesamiento_datos/contenido:/app/contenido
      - ./kaggle.json:/root/.kaggle/kaggle.json:ro
    environment:
      - KAGGLE_CONFIG_DIR=/root/.kaggle
    working_dir: /app
    command: bash -c "
      python contenido/descargar_dataset.py && 
      python contenido/Corrector_de_cryptosCSV.py && 
      python contenido/Corrector_de_stocksCSV.py && 
      python contenido/subida_cryptoCSV_pandas_docker.py"
#
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=cryptobro
      - DOCKER_INFLUXDB_INIT_PASSWORD=criptobro12345
      - DOCKER_INFLUXDB_INIT_ORG=Cryptobro_Together_Strong
      - DOCKER_INFLUXDB_INIT_BUCKET=livemarket
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=solo_para_cryptobros

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./subida_y_procesamiento_datos/contenido:/app/contenido
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    depends_on:
      - python-kaggle
    ports:
      - "1880:1880"
    volumes:
      - ./subida_y_procesamiento_datos/contenido:/data
    command: bash -c "
      apt-get update && apt-get install -y curl gnupg && 
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
      apt-get install -y nodejs && 
      node -v && npm -v &&
      npm install node-red-contrib-influxdb"

volumes:
  influxdb_data:
  grafana-storage:
  nodered_data: