version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=cryptobro
      - DOCKER_INFLUXDB_INIT_PASSWORD=criptobro12345
      - DOCKER_INFLUXDB_INIT_ORG=Cryptobro_Together_Strong
      - DOCKER_INFLUXDB_INIT_BUCKET=livemarket
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
      - DOCKER_INFLUXDB_INIT_TOKEN=mi_token_super_seguro

volumes:
  influxdb_data:

